#!/usr/bin/env bash

echo "Checking nix requeriments..."
if ! command -v docker &> /dev/null
then
    echo "docker is required."
    exit 1
fi

if ! test -f "${1}"; then
  echo "Error: No R script provided. Use: rix-run <your-script>.R"
  exit 2
fi


mkdir -p rix-run-logs
COMMAND_TO_RUN="Rscript ${1}"
if [[ $* == *--targets* ]]; then
  COMMAND_TO_RUN="Rscript -e 'targets::tar_make(script = \\\"${1}\\\", store = \\\"_targets/${1}\\\")'"
elif  [[ $* == *--quarto* ]]; then 
  COMMAND_TO_RUN="quarto render \\\"${1}\\\""
fi
echo "Running \"$COMMAND_TO_RUN\"..."    
echo "Running \"$COMMAND_TO_RUN\"..." >> rix-run-logs/rix-run.logs

CURRENT_DIR=$(pwd)
NIX_TMP_DIR=$(mktemp -d /tmp/rix.XXXXXXXXX)
echo "Current directory is $CURRENT_DIR"
echo "Preparing the environment on $NIX_TMP_DIR"
RIX_R_SCRIPT_PATH="$NIX_TMP_DIR/extract.R"
cat <<EOF > "$RIX_R_SCRIPT_PATH"
args <- commandArgs(trailingOnly=TRUE)
if (length(args) > 0) {
  file_lines <- readLines(args[1])

  r_ver <- grep("^#' @rix r_ver ", file_lines, value = TRUE)
  if (length(r_ver) == 1) {
    r_ver <- sub("^#' @rix ", "", r_ver)
    r_ver <- parse(text = r_ver)
    tryCatch(
      eval(r_ver),
      error = function(e) {
        print(paste("Error r_ver:", e\$message))
      }
    )
    if (class(r_ver) != "character" && length(r_ver) == 1) {
      r_ver = "latest-upstream"
    }
  } else{
    r_ver = "latest-upstream"
  }  
  r_date <- grep("^#' @rix date ", file_lines, value = TRUE)
  if (length(r_date) == 1) {
    r_date <- sub("^#' @rix ", "", r_date)
    r_date <- parse(text = r_date)
    tryCatch(
      eval(r_date),
      error = function(e) {
        print(paste("Error r_date:", e\$message))
      }
    )
    if (class(r_date) != "character" && length(r_date) == 1) {
      r_date = NULL
    }
  } else{
    r_date = NULL
  }
  r_pkgs <- grep("^#' @rix r_pkgs ", file_lines, value = TRUE)
  if (length(r_pkgs) == 1) {
    r_pkgs <- sub("^#' @rix ", "", r_pkgs)
    r_pkgs <- parse(text = r_pkgs)
    tryCatch(
      eval(r_pkgs),
      error = function(e) {
        print(paste("Error r_pkgs:", e\$message))
      }
    )
    if (class(r_pkgs) != "character") {
      r_pkgs = NULL
    }
  } else{
    r_pkgs = NULL
  }      
  system_pkgs <- grep("^#' @rix system_pkgs ", file_lines, value = TRUE)
  if (length(system_pkgs) == 1) {
    system_pkgs <- sub("^#' @rix ", "", system_pkgs)
    system_pkgs <- parse(text = system_pkgs)
    tryCatch(
      eval(system_pkgs),
      error = function(e) {
        print(paste("Error system_pkgs:", e\$message))
      }
    )
    if (class(system_pkgs) != "character") {
      system_pkgs = NULL
    }
  } else{
    system_pkgs = NULL
  }
  git_pkgs <- grep("^#' @rix git_pkgs ", file_lines, value = TRUE)
  if (length(git_pkgs) == 1) {
    git_pkgs <- sub("^#' @rix ", "", git_pkgs)
    git_pkgs <- parse(text = git_pkgs)
    tryCatch(
      eval(git_pkgs),
      error = function(e) {
        print(paste("Error git_pkgs:", e\$message))
      }
    )
    if (class(git_pkgs) != "list") {
      git_pkgs = NULL
    }
  } else{
    git_pkgs = NULL
  }
  shell_hook <- grep("^#' @rix shell_hook ", file_lines, value = TRUE)
  if (length(shell_hook) == 1) {
    shell_hook <- sub("^#' @rix ", "", shell_hook)
    shell_hook <- parse(text = shell_hook)
    tryCatch(
      eval(shell_hook),
      error = function(e) {
        print(paste("Error shell_hook:", e\$message))
      }
    )
    if (class(shell_hook) != "character" && length(shell_hook) == 1) {
      shell_hook = NULL
    }
  } else{
    shell_hook = NULL
  }
}
suppressMessages(suppressWarnings({
  if(!requireNamespace("rix")) {
    install.packages("rix", repos = c(
      "https://ropensci.r-universe.dev",
      "https://cloud.r-project.org"
    ))
  }
  library(rix)
  path_default_nix <- "."  
  # print(paste0("r_ver: ",r_ver, "\n"))
  # print(paste0("date: ",r_date, "\n"))
  rix::rix(
    r_ver = r_ver,
    date = r_date,
    r_pkgs = r_pkgs,
    system_pkgs = system_pkgs,
    git_pkgs = git_pkgs,
    overwrite = TRUE,
    print = TRUE,
    project_path = path_default_nix,
    ide = "none",
    shell_hook = shell_hook
  )
}))
EOF


# docker run --rm -it \
#   -v "$PWD:/workspace" \
#   -v "$NIX_TMP_DIR:/rix" -w /workspace \
#   -e TZ=UTC \
#   nixos/nix sh -c "
# echo \"Running $COMMAND_TO_RUN\"
# "

USER_ID=$(whoami)

docker run --rm -it \
  -v "$PWD:/workspace" \
  -v "$NIX_TMP_DIR:/rix" -w /workspace \
  -e TZ=UTC \
  -e HOST_UID=$(id -u) \
  -e HOST_GID=$(id -g) \
  nixos/nix sh -c "
cd /rix
curl -sl https://raw.githubusercontent.com/ropensci/rix/refs/heads/main/inst/extdata/default.nix > rix.nix
nix-env -iA cachix -f https://cachix.org/api/v1/install
cachix use rstats-on-nix
nix-shell rix.nix --run 'Rscript -e \"rix::rix_init(project_path = \\\".\\\")\"'
nix-shell rix.nix --run 'Rscript extract.R /workspace/${1}' >> /workspace/rix-run-logs/rix-run-extract.log
cp default.nix /workspace/rix-run-logs/rix-run-extracted.nix
mv default.nix /rix/rix-run-extracted.nix
cd /workspace
if [ -f /workspace/.Rprofile ]; then
  cp /workspace/.Rprofile /workspace/.Rprofile-before  
fi
cp /rix/.Rprofile /workspace/.Rprofile
echo \"Running $COMMAND_TO_RUN\"
nix-shell /rix/rix-run-extracted.nix --run \"$COMMAND_TO_RUN\" > /workspace/rix-run-logs/rix-run-last.log
rm /workspace/.Rprofile
if [ -f /workspace/.Rprofile-before ]; then  
  mv /workspace/.Rprofile-before /workspace/.Rprofile
fi
chown -R \$HOST_UID:\$HOST_GID /workspace/
echo \"Permissions changed to \$HOST_UID:\$HOST_GID\"
" > rix-run-logs/docker_last.log
cat rix-run-logs/docker_last.log >> rix-run-logs/docker.log


